apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  host: BASE64_ENCODED_MONGODB_HOST
  username: BASE64_ENCODED_MONGODB_USERNAME
  password: BASE64_ENCODED_MONGODB_PASSWORD