name: Deploy Infrastructure

on:
  # push:
  #  branches:
  #    - main
  workflow_dispatch:
    inputs:
      AWS_REGION:
        description: 'AWS region in which to deploy the infrastructure'
        required: true
        default: 'us-east-1'
      NAME_PREFIX:
        description: 'Prefix name for resources to be created: s3 bucket, vpc, eks, ec2, lab, dev, etc.'
        required: true
        default: 'eks'
      WORKER_NODES_NUMBER:
        description: 'Number of worker nodes in eks_cluster'
        required: true
        type: choice
        options:
          - 1
          - 2
          - 3
          - 4
          - 5
        default: '3'
      WORKER_NODES_TYPE:
        description: 'Worker nodes type in eks_cluster'
        required: true
        default: 't3.medium'
      PUBLIC_SSH_KEY:
        description: 'Public ssh key to connect to ec2 host'
        required: true
        default: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDClXPdY5zEKdlNsmTVQL2mo7ilytQblt2r8M4qiULChbWCJj75ggTJUkrXcsSZbHzweaADAAlgnRURFVqNZOZrA/2eA4M85BVLHM6CGpQPO2Uh4M6D8dpSZAgSmqnNUlm0T0IpsZJ9Cb3KG1EhC8sAvV4wwqQGgJ45lwmhM36o+2yM9tgxaUfINTRFFcYP+/gY8gPAQpbgrCTvAF2n1VtqKoH5cnYEEEG0QpVTAtKeFRIkPltFRCmLnLbeX3okOrpcIxySh3tC+OobLypq8q+PQSWBrIMOVf1nHPopRKPSRehY9Qg+E+xDWUk172gekkuyGnlSwDO1yTbHFrvR3MfT3m4UxZIbI9AOr7QH0ONqTn447bbVfnnN0vH4nuP6dscRVOBe77xSk+6Wfmh6VmuEY+E1bH3aKtBWOzhGcN5wD1LT+x+9pbomthKUS21mF7tJrBNTBaXeGywOdBlcVE7pANR+riZHSwDXLEfLPOCNYY0vye1BL5TzI2eZKh+czKT2cU8Ry6DazuP8ZjTRuZ73Ae1UQpdjWJ3z26tFbkGJfFcNnqaIZGxJcEAM3jUXjVR28rH7O4uWWOFmn2ucdfPrHf8cZzi5FM9ndPRvoaWGkZYE+fZ91GvZHrrAJ00Ppqf0MRHAiqYUGw1r88w7qsEy2/y8KBiTtCF9bJiJ2fLKUQ== akbar@BAMF'

jobs:
  deploy:
    name: Deploy AWS infrastructure to host EKS (VPC, EKS, Node Group, S3, etc.)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # pin@v2

      - name: Setup tool - install Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # pin@v2
        with:
          terraform_version: 1.5.2
          terraform_wrapper: false

      - name: Setup tool - install AWS cli
        uses: unfor19/install-aws-cli-action@457b7980b125044247e455d87b9a26fc2299b787 # pin@v1

      - name: Prerequisite - Github actor name control to convert to the expected format (underscore and uppercase removed and size limited to 10 chars)
        id: github_name_control
        run: |
          ./github_actor_name_control.sh ${{ github.actor }} >> ACTOR
          cat ACTOR
          echo "ACTOR_PREFIX=$(cat ACTOR)" >> $GITHUB_ENV
          echo ${{ env.ACTOR_PREFIX }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./scripts
        shell: bash

      - name: Prerequisite - Check if exists or Create S3 Bucket for tfstate
        id: s3
        run: ./check_s3_bucket.sh ${{ github.event.inputs.NAME_PREFIX }} ${{ env.ACTOR_PREFIX }} ${{ github.event.inputs.AWS_REGION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ github.event.inputs.AWS_REGION }}
        working-directory: ./scripts
        shell: bash

      - name: Init - Terraform Init
        id: init
        run: terraform init -backend-config="bucket=${{ github.event.inputs.NAME_PREFIX }}-${{ env.ACTOR_PREFIX }}-s3-tfstate" -backend-config="key=${{ github.event.inputs.NAME_PREFIX }}-infra.tfstate" -backend-config="region=${{ github.event.inputs.AWS_REGION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ github.event.inputs.AWS_REGION }}
        working-directory: ./terraform/aws_infra
        shell: bash

      - name: Validate - Terraform Validate
        id: validate
        run: terraform validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ github.event.inputs.AWS_REGION }}
        working-directory: ./terraform/aws_infra
        shell: bash

      - name: Deploy infra - Terraform Apply
        id: apply
        run: |
          terraform apply -var="region=${{ github.event.inputs.AWS_REGION }}" -var="name_prefix=${{ github.event.inputs.NAME_PREFIX }}-${{ env.ACTOR_PREFIX }}" -var="worker_nodes_desired_size=${{ github.event.inputs.WORKER_NODES_NUMBER }}" -var="worker_nodes_type=${{ github.event.inputs.WORKER_NODES_TYPE }}" -var="public_ssh_key=${{ github.event.inputs.PUBLIC_SSH_KEY }}" -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ github.event.inputs.AWS_REGION }}
        working-directory: ./terraform/aws_infra
        shell: bash

      - name: set env from tf_output
        id: tf_output
        run: |
          echo "EKS_CLUSTER_NAME=$(terraform output cluster_name)" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ github.event.inputs.AWS_REGION }}
        working-directory: ./terraform/aws_infra
        shell: bash

      - name: Download ansible inventory and cluster name created during build phase
        id: download_inventory
        run: |
          aws s3 cp s3://${{ github.event.inputs.NAME_PREFIX }}-${{ env.ACTOR_PREFIX }}-s3-tfstate/ansible_inventory.ini .
          aws s3 cp s3://${{ github.event.inputs.NAME_PREFIX }}-${{ env.ACTOR_PREFIX }}-s3-tfstate/cluster_name.txt .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ github.event.inputs.AWS_REGION }}
        working-directory: ./ansible
        shell: bash

      - name: Install Tools on ec2 - Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@5d970176ea4bfd99a3f5004d48e293fe0994eda1 # pin@v2
        with:
          # Required, playbook filepath
          playbook: install-tools.yml
          # Directory where playbooks live
          directory: ./ansible
          # SSH private key to connect to host
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, additional flags to pass to ansible-playbook
          options: |
            --inventory ansible_inventory.ini
            --extra-vars target="dev-mongodb"
            --extra-vars pc_access_key=${{ secrets.PC_ACCESS_KEY }}
            --extra-vars pc_secret_key=${{ secrets.PC_SECRET_KEY }}
            --extra-vars AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            --extra-vars AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            --extra-vars AWS_DEFAULT_REGION=${{ github.event.inputs.AWS_REGION }}
            --extra-vars EKS_CLUSTER_NAME=${{ env.EKS_CLUSTER_NAME }}
